I = imread('C:\Users\giris\Downloads\hinge.pnm');
subplot(2,1,1);
imshow(I);
title('Original Image');
sigma = 2;
threshold = 0.01;
k = 0.04;
[Ix, Iy] = gradient(double(I));
Ix2 = Ix.^2;
Iy2 = Iy.^2;
Ixy = Ix .* Iy;
h = fspecial('gaussian', [3 3], sigma);
Ix2 = imfilter(Ix2, h, 'replicate');
Iy2 = imfilter(Iy2, h, 'replicate');
Ixy = imfilter(Ixy, h, 'replicate');
R = (Ix2.*Iy2 - Ixy.^2) - k*(Ix2 + Iy2).^2;
corners = imregionalmax(R);
corners(R <= threshold * max(R(:))) = 0;
[r, c] = find(corners);
subplot(2,1,2);
imshow(I);
title('Corner Detection Keys');
hold on;
plot(c, r, 'g*');
